name: Check self-hosted runners and file issue

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

permissions:
  actions: read
  contents: read
  issues: write

jobs:
  guard-self-hosted:
    runs-on: ubuntu-latest
    env:
      REQUIRED_LABELS: "self-hosted,Linux,X64"
      ISSUE_FILE: ".github/runner-unavailable.md"
      ISSUE_TITLE: "No self-hosted runners available for labels: self-hosted,linux,x64"
    steps:
      - name: Check runner availability (uses PAT with Admin:read)
        id: check
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.REPO_ADMIN_TOKEN }}   # PAT with Repository Administration: Read + Issues RW
          script: |
            const required = process.env.REQUIRED_LABELS.split(',').map(s=>s.trim()).filter(Boolean);

            const runners = await github.paginate(
              github.rest.actions.listSelfHostedRunnersForRepo,
              { owner: context.repo.owner, repo: context.repo.repo, per_page: 100 }
            );

            const matchingOnline = runners.filter(r =>
              r.status === 'online' &&
              required.every(req => r.labels.some(l => l.name === req))
            );

            core.info(`Found ${matchingOnline.length} matching online runner(s).`);
            core.setOutput('ok', String(matchingOnline.length > 0));
            core.setOutput('count', String(matchingOnline.length));

      - name: Prepare issue body
        if: steps.check.outputs.ok != 'true'
        run: |
          mkdir -p .github
          {
            echo "# 🚨 No self-hosted runners available"
            echo
            echo "- **Required labels:** \`${REQUIRED_LABELS}\`"
            echo "- **Detected online runners with these labels:** ${{ steps.check.outputs.count }}"
            echo "- **Workflow:** ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
            echo "- **When:** $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
            echo
            echo "Please investigate the self-hosted runner fleet (power, network, service status, or label drift)."
          } > "${ISSUE_FILE}"

      # ---------- De-dupe WITHOUT using the deprecated search API ----------
      - name: Find existing open issue with same title (no search API)
        if: steps.check.outputs.ok != 'true'
        id: find_issue
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.REPO_ADMIN_TOKEN }}
          script: |
            const title = process.env.ISSUE_TITLE;

            // Paginate all OPEN issues and look for exact title match
            const issues = await github.paginate(
              github.rest.issues.listForRepo,
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
                per_page: 100
              }
            );

            const hit = issues.find(i => i.title === title);
            core.setOutput('issue_number', hit ? String(hit.number) : '');
            core.setOutput('found', hit ? 'true' : 'false');

      - name: Comment on existing issue
        if: steps.find_issue.outputs.found == 'true'
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.REPO_ADMIN_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: Number("${{ steps.find_issue.outputs.issue_number }}"),
              body: `Another detection at ${new Date().toISOString()}.\n\nWorkflow: ${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`
            });

      - name: Create issue (from file)
        if: steps.check.outputs.ok != 'true' && steps.find_issue.outputs.found != 'true'
        uses: peter-evans/create-issue-from-file@v5
        with:
          token: ${{ secrets.REPO_ADMIN_TOKEN }}   # or omit to use GITHUB_TOKEN
          title: ${{ env.ISSUE_TITLE }}
          content-filepath: ${{ env.ISSUE_FILE }}
          labels: runner:offline, infra

